#!/bin/bash

SERVER_LIST=/home/mobaxterm/server_list

#如果不提供参数，打印server列表
if [ $# = 0 ]; then
    cat $SERVER_LIST
    exit 0
fi

function help(){

echo "
Usage: see [OPTION] [ID] [KEYWORD] [IP] [HOSTNAME]
List servers with matched KEYWORD, or ssh to it if only one server matched

  -s    reslove hostname by DNS query
  -h    print help
  
eg.

  see
		print entire server list
  see 1
		ssh to the server that ID is 1
  see 10.1.1.1
		ssh to the server that IP is 10.1.1.1
  see nas
		list the servers matched "nas"
  see nas-1
		ssh to the server nas-1(that is already in server list)
  see -s web01.example.com
		ssh to the server that hostname is web01.example.com
		
server list
  you can find server list at here: /home/mobaxterm/server_list
  "

}

#服务器连接函数
function connect(){
    echo "connect to $1 ..."
    ssh jack.fang@rootbrg@$1@10.26.2.53
    exit 0
}

#根据域名解析ip地址
function get_ip_by_name(){
    if [ ! $1 ]; then
        echo "please provide server name"
        exit 1
    fi
    IP=$(host $1 | grep "[[:digit:]]\{1,3\}.[[:digit:]]\{1,3\}.[[:digit:]]\{1,3\}.[[:digit:]]\{1,3\}" | cut -d ' ' -f4 | uniq)
    IP=$(echo $IP | cut -d ' ' -f1)
    if [ $IP ]; then
        echo "$1[$IP]"
    else
        exit 1
    fi
}



#服务器信息解析函数
function parse_server(){

    #检查参数是否是IP地址
    echo $1 | egrep "^[[:digit:]]\{1,3\}.[[:digit:]]\{1,3\}.[[:digit:]]\{1,3\}.[[:digit:]]\{1,3\}" >> /dev/null
    if [ $? = 0 ]; then
        SERVER_IP=$1
    fi

    #命令行参数是否是server ID（INDEX）
    echo $1 | grep ^[[:digit:]]*$ >>/dev/null
    if [ $? = 0 ]; then
        INDEX=$1
    else
        SERVER_NAME=$1
    fi
}



#连接至服务器列表主机
function see_server(){

    if [ $SERVER_IP ]; then
        connect $SERVER_IP

    fi


    #根据INDEX或SERVER_NAME检索服务器
    if [ $INDEX ]; then
        MATCH_COUNT=$(grep -c "^$INDEX[[:space:]]" $SERVER_LIST)
        SERVER_INFO=$(grep "^$INDEX[[:space:]]" $SERVER_LIST)
    else
        MATCH_COUNT=$(grep -c "$SERVER_NAME" $SERVER_LIST)
        SERVER_INFO=$(grep "$SERVER_NAME" $SERVER_LIST)
    fi

    #未找到服务器
    if [ $MATCH_COUNT = 0 ]; then
        echo "error: server not found"
        exit 1

    #找到多个服务器
    elif [ $MATCH_COUNT -gt 1 ]; then
        echo "servers maybe you need:"
        echo "$SERVER_INFO"
        exit 1

    #定位到唯一一台服务器
    else
        SERVER_NAME=$(echo $SERVER_INFO | cut -d ' ' -f2)
        SERVER_IP=$(echo $SERVER_INFO | cut -d ' ' -f3)
        echo "$SERVER_NAME[$SERVER_IP]"
        connect $SERVER_IP

    fi

}




case $1 in
-s)
    get_ip_by_name $2
    connect $IP
    ;;
-h)
    help
    exit 0
    ;;
-*)
    help
    exit 2
    ;;

*)
    parse_server $1
    see_server
    ;;
esac

