#!/bin/bash

SERVER_LIST=/home/mobaxterm/server_list
IS_HOSTNAME=0
USE_ANSIBLE=0
NEED_HELP=0
SERVER_IP=0
ARGC=$#
ARGV=($*)


#如果不提供参数，打印server列表
if [ $ARGC = 0 ]; then
    cat $SERVER_LIST
    exit 0
fi

function print_help(){

echo "
Usage: see [OPTION] [ID] [KEYWORD] [IP] [HOSTNAME]
List servers with matched KEYWORD, or ssh to it if only one server matched

  -a    use ansible account to login server
  -s    reslove hostname by DNS query
  -h    print help
  
eg.

  see
		print entire server list
  see 1
		ssh to the server that ID is 1
  see 10.1.1.1
		ssh to the server that IP is 10.1.1.1
  see nas
		list the servers matched "nas"
  see nas-1
		ssh to the server nas-1(that is already in server list)
  see -s web01.example.com
		ssh to the server that hostname is web01.example.com
  see -a 10.1.1.1
        ssh to server 10.1.1.1 with ansible account
  see -a -s web01.example.com		
		ssh to the server that hostname is web01.example.com with ansible account

server list
  you can find server list at here: /home/mobaxterm/server_list
  "

}

#服务器连接函数
function connect(){
    if [ $USE_ANSIBLE -eq 1 ]; then
        echo "connect to $1 with ansible ..."
        sshpass -f ~/.see/pass_a ssh ansible@$1
    else
        echo "connect to $1 ..."
        sshpass -f ~/.see/pass ssh jack.fang@rootbag@$1@10.167.146.141 #Jump server IP
        #10.67.246.241
        #10.25.2.53

    fi
    exit 0
}


#根据域名解析ip地址
function get_ip_by_name(){
    if [ ! $1 ]; then
        echo "please provide server name"
        return 1
    fi
    IP=$(host $1 | grep "[[:digit:]]\{1,3\}.[[:digit:]]\{1,3\}.[[:digit:]]\{1,3\}.[[:digit:]]\{1,3\}" | cut -d ' ' -f4 | uniq)
    IP=$(echo $IP | cut -d ' ' -f1)
    if [ $IP ]; then
        echo "$1[$IP]"
        SERVER_IP=$IP
    else
        return 1
    fi
}



#服务器信息解析函数
function parse_server(){

    #检查参数是否是IP地址
    echo $1 | egrep "^[[:digit:]]\{1,3\}.[[:digit:]]\{1,3\}.[[:digit:]]\{1,3\}.[[:digit:]]\{1,3\}" >> /dev/null
    if [ $? = 0 ]; then
        SERVER_IP=$1
		return 0
    fi

    #命令行参数是否是server ID（INDEX）
    echo $1 | grep ^[[:digit:]]*$ >>/dev/null
    if [ $? = 0 ]; then
        INDEX=$1
    else
        SERVER_NAME=$1
    fi
}



#连接至服务器列表主机
function see_server(){

    if [ ! $SERVER_IP = 0 ]; then
        connect $SERVER_IP
		return 0
    fi


    #根据INDEX或SERVER_NAME检索服务器
    if [ $INDEX ]; then
        MATCH_COUNT=$(grep -c "^$INDEX[[:space:]]" $SERVER_LIST)
        SERVER_INFO=$(grep "^$INDEX[[:space:]]" $SERVER_LIST)
    else
        MATCH_COUNT=$(grep -c "$SERVER_NAME" $SERVER_LIST)
        SERVER_INFO=$(grep "$SERVER_NAME" $SERVER_LIST)
    fi

    #未找到服务器
    if [ $MATCH_COUNT = 0 ]; then
        echo "error: server not found"
        exit 1

    #找到多个服务器
    elif [ $MATCH_COUNT -gt 1 ]; then
        echo "servers maybe you need:"
        echo "$SERVER_INFO"
        exit 0

    #定位到唯一一台服务器
    else
        SERVER_NAME=$(echo $SERVER_INFO | cut -d ' ' -f2)
        SERVER_IP=$(echo $SERVER_INFO | cut -d ' ' -f3)
        echo "$SERVER_NAME[$SERVER_IP]"
        connect $SERVER_IP

    fi

}


#解析参数
function parse_args(){
    #echo "parse args"
    for (( i=0; i<$ARGC; i++ )) do
        #echo ${ARGV[$i]}
        case ${ARGV[$i]} in
        -s)
            IS_HOSTNAME=1
            unset ARGV[$i]
            ;;
        -a)
            USE_ANSIBLE=1
            unset ARGV[$i]
            ;;
        -h)
            NEED_HELP=1
            unset ARGV[$i]
            ;;
        -*)
            unset ARGV[$i]
            ;;
        esac
    done

    ARGV=(${ARGV[*]})

}


#主函数
function run() {
    parse_args

    if [ $NEED_HELP -eq 1 ]; then
        print_help
    elif [ $IS_HOSTNAME -eq 1 ]; then
        get_ip_by_name $ARGV
        connect $SERVER_IP
    else
        parse_server $ARGV
        see_server
    fi

}


run



